version: "3.8"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-app_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: local.Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./Cargo.toml
          target: /app/Cargo.toml
