version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
